mode:
  type: Standalone
  repository:
    type: JDBC


dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/ds0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: www.3power.CN
    maxPoolSize: 10

rules:
  - !SHARDING
    tables:
      t_order:
        actualDataNodes: ds_0.t_order_vip,ds_0.t_order_normal
        tableStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithmName: t_order_inline
        keyGenerateStrategy:
          column: order_id
          keyGeneratorName: snowflake_generator

      order_vip:
        actualDataNodes: ds_0.t_order_vip
        tableStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithmName: t_order_inline
        keyGenerateStrategy:
          column: order_id
          keyGeneratorName: snowflake_generator

    shardingAlgorithms:
      t_order_inline:
        type: CLASS_BASED
        props:
          strategy: STANDARD
          algorithmClassName: shardingsphere.example.mybatis.custom.algorithm.CustomOrderIdAlgorithm

    keyGenerators:
      snowflake_generator:
        type: SNOWFLAKE


props:
  sql-show: true
